export enum PropertyTaxType {
  CITY_TAX = 'CITY_TAX',
  TOURIST_TAX = 'TOURIST_TAX',
  VAT = 'VAT',
  SERVICE_TAX = 'SERVICE_TAX',
  OCCUPANCY_TAX = 'OCCUPANCY_TAX',
  RESORT_FEE = 'RESORT_FEE',
  ENVIRONMENTAL_TAX = 'ENVIRONMENTAL_TAX'
}
