export const BOOKING_ERROR_CODES = {
  BOOKING_MISSING_REQUIRED_GUEST_INFO: 'BOOKING_MISSING_REQUIRED_GUEST_INFO', //'Missing required guest info
  BOOKING_RESERVATION_LIST_EMPTY: 'BOOKING_RESERVATION_LIST_EMPTY', //'Reservation list is empty'
  BOOKING_MISSING_ARRIVAL_OR_DEPARTURE: 'BOOKING_MISSING_ARRIVAL_OR_DEPARTURE', //'Missing arrival or departure'
  BOOKING_DEPARTURE_MUST_BE_AFTER_ARRIVAL: 'BOOKING_DEPARTURE_MUST_BE_AFTER_ARRIVAL', //'Departure must be after arrival'
  BOOKING_ARRIVAL_CANNOT_BE_IN_THE_PAST: 'BOOKING_ARRIVAL_CANNOT_BE_IN_THE_PAST', //'Arrival cannot be in the past'
  BOOKING_HOTEL_TIMEZONE_NOT_CONFIGURED: 'BOOKING_HOTEL_TIMEZONE_NOT_CONFIGURED', //'Hotel timezone not configured'
  BOOKING_HOTEL_CONFIGURATION_NOT_FOUND_CONFIG_VALUE:
    'BOOKING_HOTEL_CONFIGURATION_NOT_FOUND_CONFIG_VALUE', //'Hotel configuration not found configValue'
  BOOKING_HOTEL_CLOSING_HOURS_NOT_CONFIGURED: 'BOOKING_HOTEL_CLOSING_HOURS_NOT_CONFIGURED' //'Hotel closing hours not configured'
};
