export const ENV_CONST = {
  PORT: "PORT",
  ALLOW_ORIGINS: "ALLOW_ORIGINS",

  HOTEL_SERVICE_HOST: "HOTEL_SERVICE_HOST",
  HOTEL_SERVICE_PORT: "HOTEL_SERVICE_PORT",

  PLATFORM_SERVICE_HOST: "PLATFORM_SERVICE_HOST",
  PLATFORM_SERVICE_PORT: "PLATFORM_SERVICE_PORT",

  RMQ_URL: "RMQ_URL",
  RMQ_QUEUE: "RMQ_QUEUE",
  RMQ_HEARTBEAT: "RMQ_HEARTBEAT",

  REDIS_HOST: "REDIS_HOST",
  REDIS_PORT: "REDIS_PORT",
  REDIS_USERNAME: "REDIS_USERNAME",
  REDIS_PASSWORD: "REDIS_PASSWORD",

  SHOW_SWAGGER: "SHOW_SWAGGER",

  AUTH0_API_KEY: "AUTH0_API_KEY",
  AUTH0_DOMAIN: "AUTH0_DOMAIN",
  AUTH0_AUDIENCE: "AUTH0_AUDIENCE",

  AUTH0_DEFAULT_PASSWORD: "AUTH0_DEFAULT_PASSWORD",
  AUTH0_MM_DOMAIN: "AUTH0_MM_DOMAIN",
  AUTH0_MM_CLIENT_ID: "AUTH0_MM_CLIENT_ID",
  AUTH0_MM_CLIENT_SECRET: "AUTH0_MM_CLIENT_SECRET",

  // For chunk size of APIs
  DAILY_RATE_PLAN_PRICING_BREAKDOWN_CHUNK_SIZE: "DAILY_RATE_PLAN_PRICING_BREAKDOWN_CHUNK_SIZE",
};
