export const ENVIRONMENT = {
  PORT: 'PORT',
  HOST: 'HOST',
  ALLOW_ORIGINS: 'ALLOW_ORIGINS',
  NODE_ENV: 'NODE_ENV',

  // Redis
  REDIS_URL: 'REDIS_URL',
  BULL_APALEO_BOOKING_QUEUE: 'BULL_APALEO_BOOKING_QUEUE',
  BULL_RESERVATION_QUEUE: 'BULL_RESERVATION_QUEUE',

  // S3
  S3_BUCKET_NAME: 'S3_BUCKET_NAME',
  S3_REGION: 'S3_REGION',
  S3_ACCESS_KEY_ID: 'S3_ACCESS_KEY_ID',
  S3_SECRET_ACCESS_KEY: 'S3_SECRET_ACCESS_KEY',
  S3_CDN_ENABLED: 'S3_CDN_ENABLED',
  S3_CDN_URL: 'S3_CDN_URL',

  // Quicksight
  QUICKSIGHT_ACCESS_KEY: 'QUICKSIGHT_ACCESS_KEY',
  QUICKSIGHT_SECRECT_KEY: 'QUICKSIGHT_SECRECT_KEY',
  QUICKSIGHT_DASHBOARD_ID: 'QUICKSIGHT_DASHBOARD_ID',
  QUICKSIGHT_AWS_ACCOUNT_ID: 'QUICKSIGHT_AWS_ACCOUNT_ID',
  QUICKSIGHT_AWS_USER_ARN: 'QUICKSIGHT_AWS_USER_ARN',
  QUICKSIGHT_REGION: 'QUICKSIGHT_REGION',
  QUICKSIGHT_USER_EMAIL: 'QUICKSIGHT_USER_EMAIL',

  // SendGrid
  SENDGRID_API_KEY: 'SENDGRID_API_KEY',
  SENDGRID_SENDER_EMAIL: 'SENDGRID_SENDER_EMAIL',
  SENDGRID_SENDER_NAME: 'SENDGRID_SENDER_NAME',
  SENDGRID_TEMPLATE_NEW_SIGN_UP_EMAIL_SENDER_NAME:
    'SENDGRID_TEMPLATE_NEW_SIGN_UP_EMAIL_SENDER_NAME',
  SENDGRID_TEMPLATE_NEW_SIGN_UP_EMAIL_TO: 'SENDGRID_TEMPLATE_NEW_SIGN_UP_EMAIL_TO',
  SENDGRID_TEMPLATE_OHI_CONNECT_REQUEST_EMAIL_SENDER_NAME:
    'SENDGRID_TEMPLATE_OHI_CONNECT_REQUEST_EMAIL_SENDER_NAME',
  SENDGRID_TEMPLATE_OHI_CONNECT_REQUEST_EMAIL_TO: 'SENDGRID_TEMPLATE_OHI_CONNECT_REQUEST_EMAIL_TO',
  // spring.sendgrid.sender-name="GauVendi Notifications QA"
  // spring.sendgrid.template.new-sign-up-email.sender-name="GauVendi Notifications QA"
  // spring.sendgrid.template.new-sign-up-email.to="gauvendi-tech@inipod.com"
  // spring.sendgrid.template.ohip-connect-request-email.sender-name="GauVendi Notifications QA"PO
  // spring.sendgrid.template.ohip-connect-request-email.to="gauvendi-tech@inipod.com"

  // Mongo
  MONGO_USERNAME: 'MONGO_USERNAME',
  MONGO_PASSWORD: 'MONGO_PASSWORD',
  MONGO_HOST: 'MONGO_HOST',
  MONGO_PORT: 'MONGO_PORT',
  MONGO_EMAIL_HISTORY_DB: 'MONGO_EMAIL_HISTORY_DB',

  // PDF Generation API (matches Java: core.generate-pdf.api and core.generate-pdf.api.key)
  GENERATE_PDF_API_URL: 'GENERATE_PDF_API_URL',
  GENERATE_PDF_API_KEY: 'GENERATE_PDF_API_KEY',

  // Admin Service
  REMOTE_SERVICE_ADMIN: 'REMOTE_SERVICE_ADMIN',
  ADMIN_API_KEY: 'ADMIN_API_KEY',

  // Cluster
  MAX_WORKERS: 'MAX_WORKERS',
  RMQ_URL: 'RMQ_URL',
  RMQ_QUEUE: 'RMQ_QUEUE',
  RMQ_HEARTBEAT: 'RMQ_HEARTBEAT',
  RMQ_ISE_SOCKET_QUEUE: 'RMQ_ISE_SOCKET_QUEUE',

  // PMS
  PMS_MEWS_CONNECTOR_API_URL: 'PMS_MEWS_CONNECTOR_API_URL',
  MEWS_CLIENT_TOKEN: 'MEWS_CLIENT_TOKEN',
  REMOTE_SERVICE_ENDPOINT_ITF_PAYMENT: 'REMOTE_SERVICE_ENDPOINT_ITF_PAYMENT',
  STRIPE_PUBLIC_KEY: 'STRIPE_PUBLIC_KEY',

  PMS_APALEO_API_URL: 'PMS_APALEO_API_URL',
  PMS_APALEO_IDENTITY_API_URL: 'PMS_APALEO_IDENTITY_API_URL',
  PMS_APALEO_DISTRIBUTION_API_URL: 'PMS_APALEO_DISTRIBUTION_API_URL',
  APALEO_CLIENT_ID: 'APALEO_CLIENT_ID',
  APALEO_CLIENT_SECRET: 'APALEO_CLIENT_SECRET',
  IBE_CPP_PROPOSAL_BOOKING_CONFIRMATION_URL: 'IBE_CPP_PROPOSAL_BOOKING_CONFIRMATION_URL',

  // Notification
  INCLUDE_HOTEL_EMAIL_IN_BOOKING_CONFIRMATION: 'INCLUDE_HOTEL_EMAIL_IN_BOOKING_CONFIRMATION',
  ISE_URL: 'ISE_URL',

  // ISE Recommendation
  STAY_OPTION_RECOMMENDATION_NUMBER: 'STAY_OPTION_RECOMMENDATION_NUMBER',

  // Allowed PMS
  ALLOWED_PMS: 'ALLOWED_PMS',
  IS_AWS_USER_ENABLED: 'IS_AWS_USER_ENABLED',

  RELEASE_PENDING_PAYMENT_TIME: 'RELEASE_PENDING_PAYMENT_TIME',

  // Adyen
  ADYEN_CHECKOUT_RETURN_URL: 'ADYEN_CHECKOUT_RETURN_URL',
  ADYEN_API_RETURN_FORMAT_URL: 'ADYEN_API_RETURN_FORMAT_URL',
  ADYEN_TEST_ENV: 'ADYEN_TEST_ENV',

  // Recommendation
  MAX_MULTI_ROOMS_SCORES: 'MAX_MULTI_ROOMS_SCORES'
};
