export const ENVIRONMENT = {
  PORT: 'PORT',
  ALLOW_ORIGINS: 'ALLOW_ORIGINS',
  NODE_ENV: 'NODE_ENV',
  OHIP_APP_KEY: 'OHIP_APP_KEY',

  // Remote Service
  REMOTE_SERVICE_ENDPOINT_ITF_PAYMENT: 'REMOTE_SERVICE_ENDPOINT_ITF_PAYMENT',
  REMOTE_SERVICE_ENDPOINT_SVC_NOTIFICATION: 'REMOTE_SERVICE_ENDPOINT_SVC_NOTIFICATION',
  REMOTE_SERVICE_ENDPOINT_SVC_AVAILABILITY: 'REMOTE_SERVICE_ENDPOINT_SVC_AVAILABILITY',
  REMOTE_SERVICE_ENDPOINT_SVC_CACHING: 'REMOTE_SERVICE_ENDPOINT_SVC_CACHING',

  // Adyen
  ADYEN_CHECKOUT_RETURN_URL: 'ADYEN_CHECKOUT_RETURN_URL',
  ADYEN_API_RETURN_FORMAT_URL: 'ADYEN_API_RETURN_FORMAT_URL',
  ADYEN_TEST_ENV: 'ADYEN_TEST_ENV',

  REQUEST_TIMEOUT: 30000,

  // config-kafka
  KAFKA_BROKERS: 'KAFKA_BROKERS',
  KAFKA_CLIENTID: 'KAFKA_CLIENTID',
  KAFKA_GROUPID: 'KAFKA_GROUPID',
  KAFKA_PARTITIONS: 'KAFKA_PARTITIONS',
  KAFKA_REPLICA: 'KAFKA_REPLICA',
  KAFKA_SASL_ENABLED: 'KAFKA_SASL_ENABLED',
  KAFKA_SASL_MECHANISM: 'KAFKA_SASL_MECHANISM',
  KAFKA_SSL: 'KAFKA_SSL',
  KAFKA_TOPIC_AVAILABILITY: 'KAFKA_TOPIC_AVAILABILITY',

  // secret-kafka
  KAFKA_SASL_PASSWORD: 'KAFKA_SASL_PASSWORD',
  KAFKA_SASL_USERNAME: 'KAFKA_SASL_USERNAME',

  // PCI Proxy
  // PCI_PROXY_API_KEY: 'PCI_PROXY_API_KEY',
  // PCI_PROXY_API_PASSWORD: 'PCI_PROXY_API_PASSWORD',
  // PCI_PROXY_DOMAIN_API: 'PCI_PROXY_DOMAIN_API',
  // PCI_PROXY_DOMAIN_PROXY: 'PCI_PROXY_DOMAIN_PROXY',
  // PCI_PROXY_MERCHANT_ID: 'PCI_PROXY_MERCHANT_ID'

  // PMS
  PMS_MEWS_CONNECTOR_API_URL: 'PMS_MEWS_CONNECTOR_API_URL',
  PMS_MEWS_CLIENT_TOKEN: 'PMS_MEWS_CLIENT_TOKEN',
  PMS_APALEO_API_URL: 'PMS_APALEO_API_URL',
  PMS_APALEO_IDENTITY_API_URL: 'PMS_APALEO_IDENTITY_API_URL',
  PMS_APALEO_DISTRIBUTION_API_URL: 'PMS_APALEO_DISTRIBUTION_API_URL',
  PMS_APALEO_IDENTITY_CLIENT_ID: 'PMS_APALEO_IDENTITY_CLIENT_ID',
  PMS_APALEO_IDENTITY_CLIENT_SECRET: 'PMS_APALEO_IDENTITY_CLIENT_SECRET',

  // Redis
  REDIS_URL: 'REDIS_URL',
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_USERNAME: 'REDIS_USERNAME',
  REDIS_PASSWORD: 'REDIS_PASSWORD',

  // S3
  S3_BUCKET_NAME: 'S3_BUCKET_NAME',
  S3_REGION: 'S3_REGION',
  S3_ACCESS_KEY_ID: 'S3_ACCESS_KEY_ID',
  S3_SECRET_ACCESS_KEY: 'S3_SECRET_ACCESS_KEY',
  S3_CDN_ENABLED: 'S3_CDN_ENABLED',
  S3_CDN_URL: 'S3_CDN_URL',

  // RabbitMQ
  RMQ_URL: 'RMQ_URL',
  RMQ_QUEUE: 'RMQ_QUEUE',
  RMQ_HEARTBEAT: 'RMQ_HEARTBEAT',
  ISE_RMQ_QUEUE: 'ISE_RMQ_QUEUE',
  RMQ_ISE_SOCKET_QUEUE: 'RMQ_ISE_SOCKET_QUEUE',
  RMQ_PREFETCH_COUNT: 'RMQ_PREFETCH_COUNT',

  // AI
  AI_FEATURE_RECOMMENDATION_URL: 'AI_FEATURE_RECOMMENDATION_URL'
};
