import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateHotelDbTables1757400803458 implements MigrationInterface {
    name = 'CreateHotelDbTables1757400803458'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "mapping_standard_feature" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "hotel_standard_feature_id" uuid, "mapping_standard_feature_code" character varying(255), CONSTRAINT "PK_97bf475a355b03a10ba271ff306" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_a15736374c1e4c546689a1b95e" ON "mapping_standard_feature" ("hotel_standard_feature_id", "mapping_standard_feature_code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_bee52329b7c82e9a846ad1ed86" ON "mapping_standard_feature" ("mapping_standard_feature_code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_ee50d591b0c7cfeb5fed2e668f" ON "mapping_standard_feature" ("hotel_standard_feature_id") `);
        await queryRunner.query(`CREATE TABLE "template_amenity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "icon_image_id" uuid, "name" character varying(255), "code" character varying(60), "description" character varying(500), "amenity_type" character varying(60), "pricing_unit" character varying(60), "availability" character varying(60), "post_next_day" boolean, "display_sequence" integer, CONSTRAINT "PK_5c83c37b33bb51cdc1bc0503a75" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_3a2feb46b60f406a364b436863" ON "template_amenity" ("display_sequence") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_4948e2a61d344b3ac92c3bfddd" ON "template_amenity" ("availability") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_fae5f8241e6ef84a9afa160255" ON "template_amenity" ("pricing_unit") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_3d9cd24f1778773153fa86d2f5" ON "template_amenity" ("amenity_type") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_b2994531a0a3311a13d32a2520" ON "template_amenity" ("name") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_1835eb435e618645e87f0c810c" ON "template_amenity" ("code") `);
        await queryRunner.query(`CREATE TABLE "hotel" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "deleted_at" TIMESTAMP WITH TIME ZONE, "brand_id" uuid, "icon_image_id" uuid, "email_image_id" uuid, "organisation_id" uuid, "base_currency_id" uuid, "icon_symbol_image_id" uuid, "custom_theme_image_id" uuid, "background_category_image_id" uuid, "name" character varying(255), "code" character varying(60), "status" character varying(61) DEFAULT 'ACTIVE', "email_address" jsonb, "signature" character varying(1000), "sender_name" character varying(100), "sender_email" character varying(100), "time_zone" character varying(60), "tax_setting" character varying(60) DEFAULT 'INCLUSIVE', "service_charge_setting" character varying(60) DEFAULT 'INCLUSIVE', "is_city_tax_included_selling_price" boolean NOT NULL DEFAULT false, "stay_option_background_image_id" uuid, "customize_stay_option_background_image_id" uuid, "stay_option_suggestion_image_id" uuid, "signature_background_image_id" uuid, "country_id" uuid, "lowest_price_image_id" uuid, "preferred_language_code" character varying(10), "initial_setup" boolean DEFAULT false, "phone_code" character varying(15), "phone_number" character varying(60), "room_number" integer, "city" character varying(255), "state" character varying(255), "postal_code" character varying(60), "address" character varying(1000), "address_display" text, "latitude" character varying(255), "longitude" character varying(255), "description" text, "phone" character varying(60), "measure_metric" character varying(60), CONSTRAINT "PK_3a62ac86b369b36c1a297e9ab26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_4e1924aa31055bed085a00a60b" ON "hotel" ("name") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_2f91b9aa7761020e0d4e0a9189" ON "hotel" ("status") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_43c60de2a6f8d12dd24fe2c17f" ON "hotel" ("code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_5784dab6b99190f2132c49792a" ON "hotel" ("icon_symbol_image_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_0b955f96081ce93d1419c885a4" ON "hotel" ("base_currency_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_0488d14ba6c73cb2ac2380237c" ON "hotel" ("organisation_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_9beaf75bc49ee1bf39969d8013" ON "hotel" ("icon_image_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_5c99d82207134461ec06c10bc8" ON "hotel" ("brand_id") `);
        await queryRunner.query(`CREATE TABLE "mapping_rfc_dynamic_pricing" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "hotel_id" uuid, "rate_plan_id" uuid, "room_product_id" uuid, "mapping_pms_rate_plan_code" character varying(60), CONSTRAINT "PK_33b60ef0238157e766f35cf13c6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_5c19c8e1b6e7c1dda2ea9c9852" ON "mapping_rfc_dynamic_pricing" ("room_product_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_2614bd19d6d7e68b7c2baa2602" ON "mapping_rfc_dynamic_pricing" ("rate_plan_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_208bfb79d52efdcaef86120231" ON "mapping_rfc_dynamic_pricing" ("hotel_id") `);
        await queryRunner.query(`CREATE TABLE "organisation_widget_config" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "code" character varying(100) NOT NULL, "organisation_id" uuid NOT NULL, "property_id" uuid NOT NULL, "name" character varying(255), "attribute" character varying(255) NOT NULL, "value" character varying(2000) NOT NULL, CONSTRAINT "PK_a22831f3fc9f2557218a2766ac1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_c9a285192813473199c0efc740" ON "organisation_widget_config" ("organisation_id", "property_id", "code", "attribute") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_51861fc7f98a193ba46ed095cb" ON "organisation_widget_config" ("property_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_3a984ee31a3af07214074a4430" ON "organisation_widget_config" ("organisation_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_d18d3ca2b6f79d9fa4304a7339" ON "organisation_widget_config" ("code") `);
        await queryRunner.query(`CREATE TABLE "mapping_pms_hotel" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "hotel_id" uuid, "mapping_hotel_code" character varying(60), "connector_id" uuid, CONSTRAINT "PK_3eeb9e9436e755a924965e82378" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_049d569de932c639d33ad1169c" ON "mapping_pms_hotel" ("hotel_id", "connector_id", "mapping_hotel_code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_35903cc2c38449deba0ba1926c" ON "mapping_pms_hotel" ("connector_id", "mapping_hotel_code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_778a0decf3e30163366a230c68" ON "mapping_pms_hotel" ("hotel_id", "mapping_hotel_code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_e21db383b99af09661aeb7a432" ON "mapping_pms_hotel" ("hotel_id", "connector_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_7fd7ce8ba9392cd0f15747ae66" ON "mapping_pms_hotel" ("mapping_hotel_code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_5e1aa3b6f8f6359f9d7fa7beb1" ON "mapping_pms_hotel" ("connector_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_f151dc92eef40956a4d9880929" ON "mapping_pms_hotel" ("hotel_id") `);
        await queryRunner.query(`CREATE TABLE "organisation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "code" character varying(60), "phoneCode" character varying(15), "phoneNumber" character varying(15), "email_address" jsonb, "city" character varying(60), "state" character varying(60), "country" character varying(60), "postal_code" character varying(60), "address" character varying(250), "initial_setup" boolean, "name" character varying(255), CONSTRAINT "PK_c725ae234ef1b74cce43d2d00c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_d9428f9c8e3052d6617e3aab0e" ON "organisation" ("name") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_6a3122daf3cb06cb4f1f87ae64" ON "organisation" ("code") `);
        await queryRunner.query(`CREATE TABLE "mapping_retail_feature" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "hotel_retail_feature_id" uuid, "mapping_retail_feature_code" character varying(255), CONSTRAINT "PK_d1280c7630dd39b64c8adfe168b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_1ddd207fe318c38960c15db9ad" ON "mapping_retail_feature" ("hotel_retail_feature_id", "mapping_retail_feature_code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_829e3a152b5759f946bfec00cf" ON "mapping_retail_feature" ("mapping_retail_feature_code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_38ae9466536231be8e30ae429d" ON "mapping_retail_feature" ("hotel_retail_feature_id") `);
        await queryRunner.query(`CREATE TABLE "hotel_template_email" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "hotel_id" uuid NOT NULL, "code" character varying(60) NOT NULL, "name" character varying(100), "language_code" character varying(60), "template_id" character varying(60) NOT NULL, "opening_section" text, "opening_section_for_returning_guest" text, "closing_section" text, "signature" text, "is_default" boolean DEFAULT false, "title" text, "is_enable" boolean DEFAULT true, CONSTRAINT "PK_d4bdefb0ca72c8135952c7a21fa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_ef9474f9d3534f904ca0930681" ON "hotel_template_email" ("hotel_id", "code", "language_code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_7df39267db17529bbbf46be7d8" ON "hotel_template_email" ("hotel_id", "language_code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_4badcf7a22ea89ef211bcb1907" ON "hotel_template_email" ("hotel_id", "code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_2a54484f412c59d9713a83548b" ON "hotel_template_email" ("is_enable") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_e31c10f6f40e97d041fc7d96ff" ON "hotel_template_email" ("is_default") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_d2ee7c57eff93a47ed8c4eed7b" ON "hotel_template_email" ("template_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_9add8d810a37af0a9f5576eb6b" ON "hotel_template_email" ("language_code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_ce41e1617066084ffcf09b3a77" ON "hotel_template_email" ("code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_f6f1a591523b349490897c8ec4" ON "hotel_template_email" ("hotel_id") `);
        await queryRunner.query(`CREATE TABLE "hotel_payment_term" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "translations" jsonb NOT NULL DEFAULT '[]', "hotel_id" uuid, "name" character varying(255), "code" character varying(60), "description" character varying(4000), "pay_at_hotel" numeric(26,4), "pay_at_hotel_description" character varying(4000), "pay_on_confirmation" numeric(26,4), "pay_on_confirmation_description" character varying(4000), "is_default" boolean NOT NULL DEFAULT false, "supported_payment_method_codes" jsonb, CONSTRAINT "PK_f35d2fab39a03ec8ffcc4b0fed5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_335fce84cb8b746608fbdef435" ON "hotel_payment_term" ("hotel_id", "is_default") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_ddf276961bfc95f222d5bf507b" ON "hotel_payment_term" ("hotel_id", "code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_003efd91a9e23cb846fcc12295" ON "hotel_payment_term" ("is_default") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_f0e5138cba783b019234817fd5" ON "hotel_payment_term" ("code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_b437e8bea2994281f59f61db70" ON "hotel_payment_term" ("hotel_id") `);
        await queryRunner.query(`CREATE TABLE "hotel_tax" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "translations" jsonb NOT NULL DEFAULT '[]', "hotel_id" uuid, "code" character varying(60) NOT NULL, "name" character varying(255) NOT NULL, "rate" numeric(26,4) NOT NULL, "valid_from" date, "valid_to" date, "description" character varying(1000), "mapping_pms_tax_code" character varying(100), "is_default" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_ed8e7e4064504744029aeb09f09" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_6a289696f145e4fe3af36e5218" ON "hotel_tax" ("mapping_pms_tax_code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_b9f5c711161636067016c77288" ON "hotel_tax" ("valid_to") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_62cf1dbb258545f619d3452137" ON "hotel_tax" ("valid_from") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_1bee37dba99d88f23809c331f0" ON "hotel_tax" ("is_default") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_c1058b4a3ef72c9a94efa1c046" ON "hotel_tax" ("code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_5867bfeb7fa59b4243bfc6d904" ON "hotel_tax" ("hotel_id") `);
        await queryRunner.query(`CREATE TABLE "occ_reference" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "hotel_id" uuid NOT NULL, "date" TIMESTAMP WITH TIME ZONE NOT NULL, "occ_rate" double precision DEFAULT '0', CONSTRAINT "PK_f9a817eb5fedb92ef3acee7d395" PRIMARY KEY ("id", "hotel_id", "date"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_a5bde18df75cf57a5a95759ae2" ON "occ_reference" ("hotel_id", "date") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_891f46f674ff057ba81ad49728" ON "occ_reference" ("date") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_34b6ee11bc0942c94b68bba1f0" ON "occ_reference" ("hotel_id") `);
        await queryRunner.query(`CREATE TABLE "hotel_payment_account" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "hotel_id" uuid, "payment_id" character varying(255), "origin" character varying(60), "payment_api_key" character varying(1000), "merchant" character varying(255), "live_endpoint_url_prefix" character varying(255), "environment" character varying(40), "type" character varying(60), "sub_merchant_id" character varying(60), "fee_fixed_amount" numeric(26,4), "fee_percentage" numeric(26,4), CONSTRAINT "PK_5eed78107240daa4225ce6cf67e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_a1a335bf91669136d15fb7b0b0" ON "hotel_payment_account" ("hotel_id", "origin") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_1846ada735c3ae36695393cb62" ON "hotel_payment_account" ("hotel_id", "type") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_97ecb3c611733b07ecc474a45a" ON "hotel_payment_account" ("sub_merchant_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_ad4e8dc1db08dab04aa7129098" ON "hotel_payment_account" ("environment") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_15816a7536b74302e1646419b0" ON "hotel_payment_account" ("type") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_27a8bafcabd2cf32cd133507bc" ON "hotel_payment_account" ("origin") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_23b032347d7ca43ae443a779a3" ON "hotel_payment_account" ("hotel_id") `);
        await queryRunner.query(`CREATE TABLE "hotel_market_segment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "hotel_id" uuid NOT NULL, "code" character varying(20) NOT NULL, "name" character varying(30) NOT NULL, "description" character varying(40), "status" character varying(10) NOT NULL DEFAULT 'INACTIVE', CONSTRAINT "PK_e0b262c1d73a3e85aea717139ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_b998197132531d817828ba5697" ON "hotel_market_segment" ("hotel_id", "code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_df1c77500fbfc37047221cca5b" ON "hotel_market_segment" ("status") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_1a2a14695c8f05f752507c128d" ON "hotel_market_segment" ("code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_13c54a2e7001c1a796dd7caacd" ON "hotel_market_segment" ("hotel_id") `);
        await queryRunner.query(`CREATE TABLE "hotel_city_tax" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "translations" jsonb NOT NULL DEFAULT '[]', "hotel_id" uuid, "code" character varying(60), "name" character varying(255), "unit" character varying(60), "value" numeric(26,4), "charge_method" character varying(100), "valid_from" date, "valid_to" date, "status" character varying(60), "description" character varying(1000), "mapping_pms_city_tax_code" character varying(100), CONSTRAINT "PK_54faacfee0be3d125a535d59266" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_815b7c4383423766e18549103c" ON "hotel_city_tax" ("hotel_id", "status") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_fe1cc633576c649cdc3fe10203" ON "hotel_city_tax" ("valid_to") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_974b5d084b02a053b242c2e163" ON "hotel_city_tax" ("valid_from") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_bb28a5f854991a87e97a35fa0d" ON "hotel_city_tax" ("charge_method") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_d1dc40f414b37d22ff81891874" ON "hotel_city_tax" ("unit") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_90f562d06d8ce917a69b046893" ON "hotel_city_tax" ("status") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_ee414fed590040c42b159e4096" ON "hotel_city_tax" ("code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_4502df59cfba6093a33477fd16" ON "hotel_city_tax" ("hotel_id") `);
        await queryRunner.query(`CREATE TABLE "hotel_city_tax_age_group" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "hotel_id" uuid, "hotel_city_tax_id" uuid, "from_age" integer, "to_age" integer, "value" numeric(26,4), CONSTRAINT "PK_808fe8bd00859315d570c089485" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_7dc236ba8f5a7121fa61dc8336" ON "hotel_city_tax_age_group" ("hotel_city_tax_id", "from_age", "to_age") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_f2eb5dc8ebf8fcd031b70443c1" ON "hotel_city_tax_age_group" ("to_age") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_d18c3dbcb2b3d98be7d56069e7" ON "hotel_city_tax_age_group" ("from_age") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_6778b1c98bafb068ab38c631e1" ON "hotel_city_tax_age_group" ("hotel_city_tax_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_848a397353c065d4074630dd62" ON "hotel_city_tax_age_group" ("hotel_id") `);
        await queryRunner.query(`CREATE TABLE "hotel_tax_setting" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "hotel_id" uuid, "service_code" character varying(60) NOT NULL, "service_type" character varying(255) NOT NULL, "tax_code" character varying(60) NOT NULL, "description" character varying(1000), CONSTRAINT "PK_377084a2ba2e374c08c61d3ad5f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_26eb0c5eda7d7173c10d7611d0" ON "hotel_tax_setting" ("hotel_id", "service_code", "service_type") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_8b605e29a467b40cfde5448d71" ON "hotel_tax_setting" ("hotel_id", "service_type") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_1e1f9d33f4eea631c05c9484ee" ON "hotel_tax_setting" ("hotel_id", "service_code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_2f8700121ad6a0d94411f7cd53" ON "hotel_tax_setting" ("tax_code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_de1626a3bec00dac0eb2e6c894" ON "hotel_tax_setting" ("service_type") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_34b622295ad0ecdebd9b57f8d1" ON "hotel_tax_setting" ("service_code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_f45593cb0d2d6b78dda25033d7" ON "hotel_tax_setting" ("hotel_id") `);
        await queryRunner.query(`CREATE TABLE "hotel_configuration" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "deleted_at" TIMESTAMP WITH TIME ZONE, "hotel_id" uuid, "config_value" jsonb, "config_type" character varying(60) NOT NULL, CONSTRAINT "PK_7128816ebf1688dddc9a0ec4f4e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_748c9dec2570a0524e9de6b8fe" ON "hotel_configuration" ("hotel_id", "config_type") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_8d65542b21ed1d23baf0d5e617" ON "hotel_configuration" ("config_type") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_8e73fed024f8ac0cc26b772f46" ON "hotel_configuration" ("hotel_id") `);
        await queryRunner.query(`CREATE TABLE "hotel_amenity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "translations" jsonb NOT NULL DEFAULT '[]', "hotel_id" uuid, "icon_image_id" uuid, "template_amenity_id" uuid, "name" character varying(255), "description" character varying(500), "base_rate" numeric(26,4), "amenity_type" character varying(60), "pricing_unit" character varying(60), "ise_pricing_display_mode" character varying(16), "availability" character varying(60), "post_next_day" boolean, "display_sequence" integer, "mapping_hotel_amenity_code" character varying(60), "code" character varying(60), "status" character varying(60) DEFAULT 'ACTIVE', "is_included" boolean DEFAULT false, "distribution_channel" jsonb NOT NULL DEFAULT '["GV_SALES_ENGINE","GV_VOICE"]', "selling_type" character varying(40) NOT NULL DEFAULT 'SINGLE', "linked_amenity_code" character varying(1000), CONSTRAINT "PK_3c028fa02715a28b8361eff863a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_6fcbcddcb0719642fed11b1be9" ON "hotel_amenity" ("code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_580e37607c5a78f975c9d3944a" ON "hotel_amenity" ("status") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_b7a77eca4e9fa9096cce7c148c" ON "hotel_amenity" ("amenity_type") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_d5b59d68ceccea6e079ff5dc0c" ON "hotel_amenity" ("template_amenity_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_4585bedf24786a47d1ee691c05" ON "hotel_amenity" ("icon_image_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_20f36b266666e1391a4c280df4" ON "hotel_amenity" ("hotel_id") `);
        await queryRunner.query(`CREATE TABLE "hotel_amenity_price" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "hotel_amenity_id" uuid NOT NULL, "hotel_age_category_id" uuid NOT NULL, "price" numeric(26,4) NOT NULL, CONSTRAINT "PK_d2543ae9c21ad1955b6f57e4827" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_dc32a945048bcd6adf1457b859" ON "hotel_amenity_price" ("price") `);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_1b18b3eb11d1a2a7555044ff1b" ON "hotel_amenity_price" ("hotel_amenity_id", "hotel_age_category_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_bf1eada9bc406bb9fc591b9681" ON "hotel_amenity_price" ("hotel_age_category_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_e8572aa42516d4cc6fd491c240" ON "hotel_amenity_price" ("hotel_amenity_id") `);
        await queryRunner.query(`CREATE TABLE "hotel_payment_method_setting" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "property_id" uuid, "global_payment_method_id" uuid, "global_payment_provider_id" uuid, "metadata" jsonb, "status" character varying(60), CONSTRAINT "PK_bb81933e958ee74ca73dcac24af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_d8776e591715d2b17e6ddadbb2" ON "hotel_payment_method_setting" ("property_id", "global_payment_method_id", "global_payment_provider_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_bf5d4dba94e5efc4bf72e6f92c" ON "hotel_payment_method_setting" ("property_id", "global_payment_provider_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_184acb6ddc89b4d066eb8f69e1" ON "hotel_payment_method_setting" ("property_id", "global_payment_method_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_05bfa3e31cfe036af00b9910ea" ON "hotel_payment_method_setting" ("status") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_8bcd36f44d11ac990f0771a037" ON "hotel_payment_method_setting" ("global_payment_provider_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_32ab18f5fe328d55b61e66ea4f" ON "hotel_payment_method_setting" ("global_payment_method_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_714b23d995b2257d37f389b49e" ON "hotel_payment_method_setting" ("property_id") `);
        await queryRunner.query(`CREATE TABLE "hotel_age_category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "hotel_id" uuid, "name" character varying(255), "code" character varying(60), "description" character varying(255), "from_age" integer, "to_age" integer, CONSTRAINT "PK_d8b846efd33d81415ceae911970" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_1258f4eca603b37fdf2e78e83d" ON "hotel_age_category" ("to_age") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_621723d530987b8d57ddbd817a" ON "hotel_age_category" ("from_age") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_b134b963878ec4209d0ec62d61" ON "hotel_age_category" ("code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_ac67645a950182263fea58fc64" ON "hotel_age_category" ("hotel_id") `);
        await queryRunner.query(`CREATE TABLE "event_feature" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "event_id" uuid, "hotel_retail_feature_id" uuid, CONSTRAINT "PK_ee15cf47f87f90ec495e8dff270" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_6fa5717e71fa6c79fd335cd99d" ON "event_feature" ("hotel_retail_feature_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_da4f31b4a66052e22a42b1fc31" ON "event_feature" ("event_id") `);
        await queryRunner.query(`CREATE TABLE "global_payment_method" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "deleted_at" TIMESTAMP WITH TIME ZONE, "code" character varying(60), "name" character varying(255), "description" text, "supported_payment_provider_codes" jsonb, CONSTRAINT "PK_b6daa67e692bd77eb727d523b3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_e93eea007a3e704573cccc5fd9" ON "global_payment_method" ("name") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_32919a5ab02055f5338e90becc" ON "global_payment_method" ("code") `);
        await queryRunner.query(`CREATE TABLE "event_category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "image_id" uuid, "name" character varying(255), CONSTRAINT "PK_697909a55bde1b28a90560f3ae2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_d2c138089f45f7c3fa916ffb68" ON "event_category" ("name") `);
        await queryRunner.query(`CREATE TABLE "flyway_schema_history" ("installed_rank" integer NOT NULL, "version" integer, "description" character varying(200) NOT NULL, "type" character varying(20) NOT NULL, "script" character varying(1000) NOT NULL, "checksum" integer, "installed_by" character varying(100) NOT NULL, "installed_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "execution_time" integer NOT NULL, "success" boolean NOT NULL, CONSTRAINT "PK_b944906822a82b6fa0134d09980" PRIMARY KEY ("installed_rank"))`);
        await queryRunner.query(`CREATE TABLE "global_payment_provider" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "code" character varying(60), "name" character varying(255), "description" text, "image_url" text, CONSTRAINT "PK_e1d2893a7a6a47e1f5639d92aa9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_9c1bda1595fe2ba9bf8997d7d4" ON "global_payment_provider" ("name") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_6b43b1782073d0ef158be83b58" ON "global_payment_provider" ("code") `);
        await queryRunner.query(`CREATE TABLE "hotel_cancellation_policy" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "translations" jsonb NOT NULL DEFAULT '[]', "hotel_id" uuid, "code" character varying(255), "name" character varying(255), "cancellation_type" character varying(60), "hour_prior" integer, "display_unit" character varying(60), "cancellation_fee_value" numeric(26,4), "cancellation_fee_unit" character varying(60) DEFAULT 'PERCENTAGE', "description" character varying(4000), "is_default" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_a58574c7f640d7f4ecb7375848a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_e7b4bd9abc75afd37831fdec3a" ON "hotel_cancellation_policy" ("hour_prior") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_25b5c8f5c74c006ab3f165394e" ON "hotel_cancellation_policy" ("is_default") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_139fb0273b73b53e975afb93b9" ON "hotel_cancellation_policy" ("cancellation_type") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_678bc822716e90bde66d9044c2" ON "hotel_cancellation_policy" ("code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_1fa4f037c44804e2724ee18eae" ON "hotel_cancellation_policy" ("hotel_id") `);
        await queryRunner.query(`CREATE TABLE "event_label" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "name" character varying(255) NOT NULL, CONSTRAINT "PK_b951570b91c509f6a494fe068d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "event" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "translations" jsonb NOT NULL DEFAULT '[]', "hotel_id" uuid NOT NULL, "category_id" uuid NOT NULL, "label" jsonb, "name" character varying(255) NOT NULL, "start_date" TIMESTAMP WITH TIME ZONE NOT NULL, "end_date" TIMESTAMP WITH TIME ZONE NOT NULL, "location" character varying(255), "note" text, "is_visible" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_30c2f3bbaf6d34a55f8ae6e4614" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_c69e7e727e0915c693bd131e70" ON "event" ("is_visible") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_fb931d7d954ab53421bbd19ad3" ON "event" ("end_date") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_6d225d2181fcfcebdfd7ac5365" ON "event" ("start_date") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_697909a55bde1b28a90560f3ae" ON "event" ("category_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_e4b233dc2113aad9361eb41800" ON "event" ("hotel_id") `);
        await queryRunner.query(`CREATE TABLE "hotel_payment_mode" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "hotel_id" uuid NOT NULL, "code" character varying(60) NOT NULL, "name" character varying(100), "description" text, CONSTRAINT "PK_214c1a32bff62e43960429da242" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_cc2229f2dd91199af930c0d374" ON "hotel_payment_mode" ("hotel_id", "code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_b369836b49309eb6f694603be9" ON "hotel_payment_mode" ("code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_598fc4de3fffd31b9e142efc2a" ON "hotel_payment_mode" ("hotel_id") `);
        await queryRunner.query(`CREATE TABLE "brand" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" text, "updated_by" text, "name" character varying(255) NOT NULL, CONSTRAINT "PK_a5d20765ddd942eb5de4eee2d7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "room_product_mapping_pms" DROP CONSTRAINT "FK_0ab2847d1f1262d30871ead02b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_933574ddcad8acad7b8a274c73"`);
        await queryRunner.query(`ALTER TABLE "room_product_mapping_pms" DROP CONSTRAINT "UQ_0ab2847d1f1262d30871ead02b0"`);
        await queryRunner.query(`ALTER TABLE "room_product_type_mapping" DROP CONSTRAINT "FK_fc74acb8ce5a605535dc65d15b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29edcd6224ce0e47252d1e5bba"`);
        await queryRunner.query(`ALTER TABLE "room_product_type_mapping" DROP CONSTRAINT "UQ_fc74acb8ce5a605535dc65d15b2"`);
        await queryRunner.query(`ALTER TABLE "connector" DROP CONSTRAINT "PK_6c5a19153f8f3074f2836a2b082"`);
        await queryRunner.query(`ALTER TABLE "connector" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "connector" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "connector" ADD CONSTRAINT "PK_6c5a19153f8f3074f2836a2b082" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "connector" DROP COLUMN "organisation_id"`);
        await queryRunner.query(`ALTER TABLE "connector" ADD "organisation_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "connector" DROP COLUMN "refresh_token"`);
        await queryRunner.query(`ALTER TABLE "connector" ADD "refresh_token" text`);
        await queryRunner.query(`ALTER TABLE "connector" DROP COLUMN "connector_type"`);
        await queryRunner.query(`ALTER TABLE "connector" ADD "connector_type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "connector" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "connector" ADD "status" character varying(20) NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "connector" ADD COLUMN IF NOT EXISTS "hotel_id" uuid`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_fc24100cb97a00daa984f51e2d" ON "hotel_retail_category" ("hotel_id", "category_type") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_b47c106cd5df3a464302ba02f6" ON "hotel_retail_category" ("hotel_id", "code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_1440d928138855e190d98caa24" ON "hotel_retail_category" ("hotel_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_3b852e505cc20032696c4fd635" ON "rate_plan_derived_setting" ("hotel_id", "derived_rate_plan_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_01beeadedebb419d7ecc49903c" ON "rate_plan_derived_setting" ("hotel_id", "rate_plan_id", "derived_rate_plan_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_2a90bbc9221736f02c59e3a78b" ON "rate_plan_derived_setting" ("hotel_id", "rate_plan_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_0d3b8990a314fd25da88ee693f" ON "room_product_feature_rate_adjustment" ("feature_id", "room_product_rate_plan_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_933574ddcad8acad7b8a274c73" ON "room_product_mapping_pms" ("hotel_id", "room_product_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_29edcd6224ce0e47252d1e5bba" ON "room_product_type_mapping" ("hotel_id", "room_product_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_4b877db53c31c3182c0951993f" ON "room_product_mapping" ("hotel_id", "related_room_product_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_ef85c1d8cd74bda7eb1803b3bc" ON "connector" ("status") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_0ab4ad3877d6740860ffa3103a" ON "connector" ("connector_type") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_fe73168c9ff01a8b66a88fde59" ON "connector" ("hotel_id") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_3f73543ec4fbaca6074bfd83b3" ON "connector" ("organisation_id") `);
        await queryRunner.query(`ALTER TABLE "room_product_mapping_pms" ADD CONSTRAINT "FK_0ab2847d1f1262d30871ead02b0" FOREIGN KEY ("room_product_id") REFERENCES "room_product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_product_type_mapping" ADD CONSTRAINT "FK_fc74acb8ce5a605535dc65d15b2" FOREIGN KEY ("room_product_id") REFERENCES "room_product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mapping_rfc_dynamic_pricing" ADD CONSTRAINT "FK_208bfb79d52efdcaef86120231e" FOREIGN KEY ("hotel_id") REFERENCES "hotel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mapping_rfc_dynamic_pricing" ADD CONSTRAINT "FK_2614bd19d6d7e68b7c2baa26029" FOREIGN KEY ("rate_plan_id") REFERENCES "rate_plan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mapping_rfc_dynamic_pricing" ADD CONSTRAINT "FK_5c19c8e1b6e7c1dda2ea9c9852d" FOREIGN KEY ("room_product_id") REFERENCES "room_product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel_payment_term" ADD CONSTRAINT "FK_b437e8bea2994281f59f61db70d" FOREIGN KEY ("hotel_id") REFERENCES "hotel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel_tax" ADD CONSTRAINT "FK_5867bfeb7fa59b4243bfc6d9047" FOREIGN KEY ("hotel_id") REFERENCES "hotel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel_payment_account" ADD CONSTRAINT "FK_23b032347d7ca43ae443a779a33" FOREIGN KEY ("hotel_id") REFERENCES "hotel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel_market_segment" ADD CONSTRAINT "FK_13c54a2e7001c1a796dd7caacde" FOREIGN KEY ("hotel_id") REFERENCES "hotel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel_city_tax" ADD CONSTRAINT "FK_4502df59cfba6093a33477fd165" FOREIGN KEY ("hotel_id") REFERENCES "hotel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel_city_tax_age_group" ADD CONSTRAINT "FK_848a397353c065d4074630dd627" FOREIGN KEY ("hotel_id") REFERENCES "hotel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel_city_tax_age_group" ADD CONSTRAINT "FK_6778b1c98bafb068ab38c631e14" FOREIGN KEY ("hotel_city_tax_id") REFERENCES "hotel_city_tax"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel_configuration" ADD CONSTRAINT "FK_8e73fed024f8ac0cc26b772f46c" FOREIGN KEY ("hotel_id") REFERENCES "hotel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel_amenity" ADD CONSTRAINT "FK_20f36b266666e1391a4c280df48" FOREIGN KEY ("hotel_id") REFERENCES "hotel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel_amenity" ADD CONSTRAINT "FK_d5b59d68ceccea6e079ff5dc0c6" FOREIGN KEY ("template_amenity_id") REFERENCES "template_amenity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel_age_category" ADD CONSTRAINT "FK_ac67645a950182263fea58fc64d" FOREIGN KEY ("hotel_id") REFERENCES "hotel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel_cancellation_policy" ADD CONSTRAINT "FK_1fa4f037c44804e2724ee18eaea" FOREIGN KEY ("hotel_id") REFERENCES "hotel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event" ADD CONSTRAINT "FK_e4b233dc2113aad9361eb418003" FOREIGN KEY ("hotel_id") REFERENCES "hotel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event" ADD CONSTRAINT "FK_697909a55bde1b28a90560f3ae2" FOREIGN KEY ("category_id") REFERENCES "event_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel_payment_mode" ADD CONSTRAINT "FK_598fc4de3fffd31b9e142efc2a1" FOREIGN KEY ("hotel_id") REFERENCES "hotel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "connector" ADD CONSTRAINT "FK_3f73543ec4fbaca6074bfd83b37" FOREIGN KEY ("organisation_id") REFERENCES "organisation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "connector" ADD CONSTRAINT "FK_fe73168c9ff01a8b66a88fde592" FOREIGN KEY ("hotel_id") REFERENCES "hotel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "connector" DROP CONSTRAINT "FK_fe73168c9ff01a8b66a88fde592"`);
        await queryRunner.query(`ALTER TABLE "connector" DROP CONSTRAINT "FK_3f73543ec4fbaca6074bfd83b37"`);
        await queryRunner.query(`ALTER TABLE "hotel_payment_mode" DROP CONSTRAINT "FK_598fc4de3fffd31b9e142efc2a1"`);
        await queryRunner.query(`ALTER TABLE "event" DROP CONSTRAINT "FK_697909a55bde1b28a90560f3ae2"`);
        await queryRunner.query(`ALTER TABLE "event" DROP CONSTRAINT "FK_e4b233dc2113aad9361eb418003"`);
        await queryRunner.query(`ALTER TABLE "hotel_cancellation_policy" DROP CONSTRAINT "FK_1fa4f037c44804e2724ee18eaea"`);
        await queryRunner.query(`ALTER TABLE "hotel_age_category" DROP CONSTRAINT "FK_ac67645a950182263fea58fc64d"`);
        await queryRunner.query(`ALTER TABLE "hotel_amenity" DROP CONSTRAINT "FK_d5b59d68ceccea6e079ff5dc0c6"`);
        await queryRunner.query(`ALTER TABLE "hotel_amenity" DROP CONSTRAINT "FK_20f36b266666e1391a4c280df48"`);
        await queryRunner.query(`ALTER TABLE "hotel_configuration" DROP CONSTRAINT "FK_8e73fed024f8ac0cc26b772f46c"`);
        await queryRunner.query(`ALTER TABLE "hotel_city_tax_age_group" DROP CONSTRAINT "FK_6778b1c98bafb068ab38c631e14"`);
        await queryRunner.query(`ALTER TABLE "hotel_city_tax_age_group" DROP CONSTRAINT "FK_848a397353c065d4074630dd627"`);
        await queryRunner.query(`ALTER TABLE "hotel_city_tax" DROP CONSTRAINT "FK_4502df59cfba6093a33477fd165"`);
        await queryRunner.query(`ALTER TABLE "hotel_market_segment" DROP CONSTRAINT "FK_13c54a2e7001c1a796dd7caacde"`);
        await queryRunner.query(`ALTER TABLE "hotel_payment_account" DROP CONSTRAINT "FK_23b032347d7ca43ae443a779a33"`);
        await queryRunner.query(`ALTER TABLE "hotel_tax" DROP CONSTRAINT "FK_5867bfeb7fa59b4243bfc6d9047"`);
        await queryRunner.query(`ALTER TABLE "hotel_payment_term" DROP CONSTRAINT "FK_b437e8bea2994281f59f61db70d"`);
        await queryRunner.query(`ALTER TABLE "mapping_rfc_dynamic_pricing" DROP CONSTRAINT "FK_5c19c8e1b6e7c1dda2ea9c9852d"`);
        await queryRunner.query(`ALTER TABLE "mapping_rfc_dynamic_pricing" DROP CONSTRAINT "FK_2614bd19d6d7e68b7c2baa26029"`);
        await queryRunner.query(`ALTER TABLE "mapping_rfc_dynamic_pricing" DROP CONSTRAINT "FK_208bfb79d52efdcaef86120231e"`);
        await queryRunner.query(`ALTER TABLE "room_product_type_mapping" DROP CONSTRAINT "FK_fc74acb8ce5a605535dc65d15b2"`);
        await queryRunner.query(`ALTER TABLE "room_product_mapping_pms" DROP CONSTRAINT "FK_0ab2847d1f1262d30871ead02b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f73543ec4fbaca6074bfd83b3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe73168c9ff01a8b66a88fde59"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ab4ad3877d6740860ffa3103a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef85c1d8cd74bda7eb1803b3bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b877db53c31c3182c0951993f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29edcd6224ce0e47252d1e5bba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_933574ddcad8acad7b8a274c73"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d3b8990a314fd25da88ee693f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a90bbc9221736f02c59e3a78b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01beeadedebb419d7ecc49903c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b852e505cc20032696c4fd635"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1440d928138855e190d98caa24"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b47c106cd5df3a464302ba02f6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc24100cb97a00daa984f51e2d"`);
        await queryRunner.query(`ALTER TABLE "connector" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "connector" ADD "status" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "connector" DROP COLUMN "connector_type"`);
        await queryRunner.query(`ALTER TABLE "connector" ADD "connector_type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "connector" DROP COLUMN "refresh_token"`);
        await queryRunner.query(`ALTER TABLE "connector" ADD "refresh_token" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "connector" DROP COLUMN "organisation_id"`);
        await queryRunner.query(`ALTER TABLE "connector" ADD "organisation_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "connector" DROP CONSTRAINT "PK_6c5a19153f8f3074f2836a2b082"`);
        await queryRunner.query(`ALTER TABLE "connector" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "connector" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "connector" ADD CONSTRAINT "PK_6c5a19153f8f3074f2836a2b082" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "room_product_type_mapping" ADD CONSTRAINT "UQ_fc74acb8ce5a605535dc65d15b2" UNIQUE ("room_product_id")`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_29edcd6224ce0e47252d1e5bba" ON "room_product_type_mapping" ("hotel_id", "room_product_id") `);
        await queryRunner.query(`ALTER TABLE "room_product_type_mapping" ADD CONSTRAINT "FK_fc74acb8ce5a605535dc65d15b2" FOREIGN KEY ("room_product_id") REFERENCES "room_product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_product_mapping_pms" ADD CONSTRAINT "UQ_0ab2847d1f1262d30871ead02b0" UNIQUE ("room_product_id")`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_933574ddcad8acad7b8a274c73" ON "room_product_mapping_pms" ("room_product_id", "hotel_id") `);
        await queryRunner.query(`ALTER TABLE "room_product_mapping_pms" ADD CONSTRAINT "FK_0ab2847d1f1262d30871ead02b0" FOREIGN KEY ("room_product_id") REFERENCES "room_product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`DROP TABLE "brand"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_598fc4de3fffd31b9e142efc2a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b369836b49309eb6f694603be9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc2229f2dd91199af930c0d374"`);
        await queryRunner.query(`DROP TABLE "hotel_payment_mode"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e4b233dc2113aad9361eb41800"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_697909a55bde1b28a90560f3ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d225d2181fcfcebdfd7ac5365"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb931d7d954ab53421bbd19ad3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c69e7e727e0915c693bd131e70"`);
        await queryRunner.query(`DROP TABLE "event"`);
        await queryRunner.query(`DROP TABLE "event_label"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1fa4f037c44804e2724ee18eae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_678bc822716e90bde66d9044c2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_139fb0273b73b53e975afb93b9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_25b5c8f5c74c006ab3f165394e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7b4bd9abc75afd37831fdec3a"`);
        await queryRunner.query(`DROP TABLE "hotel_cancellation_policy"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b43b1782073d0ef158be83b58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c1bda1595fe2ba9bf8997d7d4"`);
        await queryRunner.query(`DROP TABLE "global_payment_provider"`);
        await queryRunner.query(`DROP TABLE "flyway_schema_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2c138089f45f7c3fa916ffb68"`);
        await queryRunner.query(`DROP TABLE "event_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32919a5ab02055f5338e90becc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e93eea007a3e704573cccc5fd9"`);
        await queryRunner.query(`DROP TABLE "global_payment_method"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da4f31b4a66052e22a42b1fc31"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6fa5717e71fa6c79fd335cd99d"`);
        await queryRunner.query(`DROP TABLE "event_feature"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac67645a950182263fea58fc64"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b134b963878ec4209d0ec62d61"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_621723d530987b8d57ddbd817a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1258f4eca603b37fdf2e78e83d"`);
        await queryRunner.query(`DROP TABLE "hotel_age_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_714b23d995b2257d37f389b49e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32ab18f5fe328d55b61e66ea4f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8bcd36f44d11ac990f0771a037"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05bfa3e31cfe036af00b9910ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_184acb6ddc89b4d066eb8f69e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf5d4dba94e5efc4bf72e6f92c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d8776e591715d2b17e6ddadbb2"`);
        await queryRunner.query(`DROP TABLE "hotel_payment_method_setting"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e8572aa42516d4cc6fd491c240"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf1eada9bc406bb9fc591b9681"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b18b3eb11d1a2a7555044ff1b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc32a945048bcd6adf1457b859"`);
        await queryRunner.query(`DROP TABLE "hotel_amenity_price"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20f36b266666e1391a4c280df4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4585bedf24786a47d1ee691c05"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5b59d68ceccea6e079ff5dc0c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7a77eca4e9fa9096cce7c148c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_580e37607c5a78f975c9d3944a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6fcbcddcb0719642fed11b1be9"`);
        await queryRunner.query(`DROP TABLE "hotel_amenity"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e73fed024f8ac0cc26b772f46"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d65542b21ed1d23baf0d5e617"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_748c9dec2570a0524e9de6b8fe"`);
        await queryRunner.query(`DROP TABLE "hotel_configuration"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f45593cb0d2d6b78dda25033d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_34b622295ad0ecdebd9b57f8d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de1626a3bec00dac0eb2e6c894"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f8700121ad6a0d94411f7cd53"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e1f9d33f4eea631c05c9484ee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b605e29a467b40cfde5448d71"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26eb0c5eda7d7173c10d7611d0"`);
        await queryRunner.query(`DROP TABLE "hotel_tax_setting"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_848a397353c065d4074630dd62"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6778b1c98bafb068ab38c631e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d18c3dbcb2b3d98be7d56069e7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2eb5dc8ebf8fcd031b70443c1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7dc236ba8f5a7121fa61dc8336"`);
        await queryRunner.query(`DROP TABLE "hotel_city_tax_age_group"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4502df59cfba6093a33477fd16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee414fed590040c42b159e4096"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90f562d06d8ce917a69b046893"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1dc40f414b37d22ff81891874"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb28a5f854991a87e97a35fa0d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_974b5d084b02a053b242c2e163"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe1cc633576c649cdc3fe10203"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_815b7c4383423766e18549103c"`);
        await queryRunner.query(`DROP TABLE "hotel_city_tax"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13c54a2e7001c1a796dd7caacd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a2a14695c8f05f752507c128d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df1c77500fbfc37047221cca5b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b998197132531d817828ba5697"`);
        await queryRunner.query(`DROP TABLE "hotel_market_segment"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23b032347d7ca43ae443a779a3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_27a8bafcabd2cf32cd133507bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15816a7536b74302e1646419b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad4e8dc1db08dab04aa7129098"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97ecb3c611733b07ecc474a45a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1846ada735c3ae36695393cb62"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a1a335bf91669136d15fb7b0b0"`);
        await queryRunner.query(`DROP TABLE "hotel_payment_account"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_34b6ee11bc0942c94b68bba1f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_891f46f674ff057ba81ad49728"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a5bde18df75cf57a5a95759ae2"`);
        await queryRunner.query(`DROP TABLE "occ_reference"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5867bfeb7fa59b4243bfc6d904"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1058b4a3ef72c9a94efa1c046"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1bee37dba99d88f23809c331f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_62cf1dbb258545f619d3452137"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9f5c711161636067016c77288"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a289696f145e4fe3af36e5218"`);
        await queryRunner.query(`DROP TABLE "hotel_tax"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b437e8bea2994281f59f61db70"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0e5138cba783b019234817fd5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_003efd91a9e23cb846fcc12295"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ddf276961bfc95f222d5bf507b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_335fce84cb8b746608fbdef435"`);
        await queryRunner.query(`DROP TABLE "hotel_payment_term"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6f1a591523b349490897c8ec4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce41e1617066084ffcf09b3a77"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9add8d810a37af0a9f5576eb6b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2ee7c57eff93a47ed8c4eed7b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e31c10f6f40e97d041fc7d96ff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a54484f412c59d9713a83548b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4badcf7a22ea89ef211bcb1907"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7df39267db17529bbbf46be7d8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef9474f9d3534f904ca0930681"`);
        await queryRunner.query(`DROP TABLE "hotel_template_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38ae9466536231be8e30ae429d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_829e3a152b5759f946bfec00cf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ddd207fe318c38960c15db9ad"`);
        await queryRunner.query(`DROP TABLE "mapping_retail_feature"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a3122daf3cb06cb4f1f87ae64"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d9428f9c8e3052d6617e3aab0e"`);
        await queryRunner.query(`DROP TABLE "organisation"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f151dc92eef40956a4d9880929"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e1aa3b6f8f6359f9d7fa7beb1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7fd7ce8ba9392cd0f15747ae66"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e21db383b99af09661aeb7a432"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_778a0decf3e30163366a230c68"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35903cc2c38449deba0ba1926c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_049d569de932c639d33ad1169c"`);
        await queryRunner.query(`DROP TABLE "mapping_pms_hotel"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d18d3ca2b6f79d9fa4304a7339"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a984ee31a3af07214074a4430"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_51861fc7f98a193ba46ed095cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9a285192813473199c0efc740"`);
        await queryRunner.query(`DROP TABLE "organisation_widget_config"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_208bfb79d52efdcaef86120231"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2614bd19d6d7e68b7c2baa2602"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c19c8e1b6e7c1dda2ea9c9852"`);
        await queryRunner.query(`DROP TABLE "mapping_rfc_dynamic_pricing"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c99d82207134461ec06c10bc8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9beaf75bc49ee1bf39969d8013"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0488d14ba6c73cb2ac2380237c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b955f96081ce93d1419c885a4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5784dab6b99190f2132c49792a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_43c60de2a6f8d12dd24fe2c17f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f91b9aa7761020e0d4e0a9189"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e1924aa31055bed085a00a60b"`);
        await queryRunner.query(`DROP TABLE "hotel"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1835eb435e618645e87f0c810c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2994531a0a3311a13d32a2520"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d9cd24f1778773153fa86d2f5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fae5f8241e6ef84a9afa160255"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4948e2a61d344b3ac92c3bfddd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a2feb46b60f406a364b436863"`);
        await queryRunner.query(`DROP TABLE "template_amenity"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee50d591b0c7cfeb5fed2e668f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bee52329b7c82e9a846ad1ed86"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a15736374c1e4c546689a1b95e"`);
        await queryRunner.query(`DROP TABLE "mapping_standard_feature"`);
    }

}
