export enum HotelConfigurationTypeEnum {
  WHITELABEL_SETTING = 'WHITELABEL_SETTING',
  TIME_SLICE_CONFIGURATION = 'TIME_SLICE_CONFIGURATION',
  ROOM_PRODUCT_RECOMMENDATION_GRADED_LABEL_SETTING = 'ROOM_PRODUCT_RECOMMENDATION_GRADED_LABEL_SETTING',
  ROOM_PRODUCT_RECOMMENDATION_DIRECT_SETTING = 'ROOM_PRODUCT_RECOMMENDATION_DIRECT_SETTING',
  ISE_PRICING_DISPLAY = 'ISE_PRICING_DISPLAY',
  PRICING_DECIMAL_ROUNDING_RULE = 'PRICING_DECIMAL_ROUNDING_RULE'
}
