export enum ReservationStatusEnum {
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  RESERVED = 'RESERVED',
  RELEASED = 'RELEASED',
  CHECKED_IN = 'CHECKED_IN',
  CHECKED_OUT = 'CHECKED_OUT',
  COMPLETED = 'COMPLETED',
  PROPOSED = 'PROPOSED'
}
