export enum RoundingModeEnum {
  DOWN = 'DOWN',
  HALF_ROUND_UP = 'HALF_ROUND_UP',
  NO_ROUNDING = 'NO_ROUNDING',
  UP = 'UP',

  HALF_UP = 'HALF_UP'
}

export const RoundingMode = {
  UP: 0,
  DOWN: 1,
  CEILING: 2,
  FLOOR: 3,
  HALF_UP: 4,
  HALF_DOWN: 5,
  HALF_EVEN: 6,
  UNNECESSARY: 7
} as const;

export enum RatePlanAdjustmentType {
  FIXED = 'FIXED',
  PERCENTAGE = 'PERCENTAGE'
}

export enum RatePlanPaymentSettlementSettingModeEnum {
  PMS_SETTLEMENT = 'PMS_SETTLEMENT',
  MANUAL_SETTLEMENT = 'MANUAL_SETTLEMENT'
}

export enum CancellationTypeEnum {
  FREE = 'FREE',
  PARTIAL = 'PARTIAL',
  FULL = 'FULL',
  NON_REFUNDABLE = 'NON_REFUNDABLE'
}

export enum CancellationPolicyDisplayUnitEnum {
  HOUR = 'HOUR',
  DAY = 'DAY',
  WEEK = 'WEEK'
}

export enum CancellationFeeUnitEnum {
  PERCENTAGE = 'PERCENTAGE',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
  NIGHTS = 'NIGHTS'
}

// Rate Plan Enums
export enum RatePlanPricingMethodologyEnum {
  FEATURE_BASED_PRICING = 'FEATURE_BASED_PRICING',
  DERIVED_PRICING = 'DERIVED_PRICING'
}

export enum RatePlanStatusEnum {
  ACTIVE = 'ACTIVE',
  ARCHIVE = 'ARCHIVE'
}

export enum RatePlanTypeEnum {
  PUBLIC = 'PUBLIC',
  PROMOTION = 'PROMOTION',
  CORPORATE = 'CORPORATE',
  GROUP = 'GROUP',
  BUNDLE = 'BUNDLE'
}

export enum SellingStrategyTypeEnum {
  DEFAULT = 'DEFAULT',
  LONG_STAY = 'LONG_STAY'
}

export enum RatePlanAdjustmentUnitEnum {
  FIXED = 'FIXED',
  PERCENTAGE = 'PERCENTAGE'
}

// Room Unit Enums
export enum RoomUnitStatus {
  CLEAN = 'CLEAN',
  DIRTY = 'DIRTY',
  INSPECTED = 'INSPECTED',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE'
}

export enum RoomUnitAvailabilityStatus {
  AVAILABLE = 'AVAILABLE',
  ASSIGNED = 'ASSIGNED',
  OUT_OF_INVENTORY = 'OUT_OF_INVENTORY',
  OUT_OF_ORDER = 'OUT_OF_ORDER',
  BLOCKED = 'BLOCKED'
}

// Room Product Enums
export enum RoomProductStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DRAFT = 'DRAFT'
}

export enum RoomProductType {
  RFC = 'RFC',
  MRFC = 'MRFC',
  ERFC = 'ERFC'
}

export enum DistributionChannel {
  GV_SALES_ENGINE = 'GV_SALES_ENGINE',
  GV_VOICE = 'GV_VOICE',
  SITEMINDER = 'SITEMINDER'
}

export enum RfcAllocationSetting {
  ALL = 'ALL',
  DEDUCT = 'DEDUCT'
}

export enum BasePriceMode {
  FEATURE_BASED = 'FEATURE_BASED',
  AVERAGE = 'AVERAGE',
  COMBINED = 'COMBINED'
}

export enum RoomProductTypeMappingChannel {
  PMS = 'PMS',
  CM = 'CM',
  GAUVENDI = 'GAUVENDI'
}

// Room Product Rate Plan Enums
export enum RoomProductRatePlanGuaranteeTypeEnum {
  CREDIT_CARD = 'CREDIT_CARD'
}

export enum RoomProductRatePlanCancellationTypeEnum {
  FLEXIBLE = 'FLEXIBLE',
  NON_REFUNDABLE = 'NON_REFUNDABLE'
}

export enum ConfiguratorTypeEnum {
  PUSH_PMS = 'PUSH_PMS'
}

export enum ConfiguratorModeEnum {
  ENABLE = 'ENABLE',
  DISABLE = 'DISABLE'
}

// Room Product Pricing Method Enums
export enum RoomProductPricingMethodEnum {
  DERIVED = 'DERIVED',
  LINK = 'LINK',
  PRODUCT_BASED_PRICING = 'PRODUCT_BASED_PRICING',
  PMS_PRICING = 'PMS_PRICING',

  // REVERSED_PRICING = 'REVERSED_PRICING'
  REVERSED_PRICING = 'PMS_PRICING'
}

export enum RoomProductPricingMethodAdjustmentUnitEnum {
  FIXED = 'FIXED',
  PERCENTAGE = 'PERCENTAGE'
}

// Room Product Extra Enums
export enum RoomProductExtraType {
  INCLUDED = 'INCLUDED',
  EXTRA = 'EXTRA',
  MANDATORY = 'MANDATORY'
}

// Room Product Base Price Setting Enums
export enum RoomProductBasePriceSettingModeEnum {
  FEATURE_BASED = 'FEATURE_BASED',
  AVERAGE = 'AVERAGE',
  COMBINED = 'COMBINED',

  // upcoming
  FIXED_PRICE = 'FIXED_PRICE'
}

// Restriction Enums
export enum RestrictionConditionType {
  ClosedToStay = 'ClosedToStay',
  ClosedToArrival = 'ClosedToArrival',
  ClosedToDeparture = 'ClosedToDeparture'
}

// Restriction Enums
export enum RestrictionSourceType {
  MANUAL = 'MANUAL',
  AUTOMATED = 'AUTOMATED',
  DEFAULT = 'DEFAULT',
  PMS = 'PMS'
}

export enum Weekday {
  Sunday = 'Sunday',
  Monday = 'Monday',
  Tuesday = 'Tuesday',
  Wednesday = 'Wednesday',
  Thursday = 'Thursday',
  Friday = 'Friday',
  Saturday = 'Saturday'
}

export enum SeasonOfYear {
  Winter = 'Winter',
  Summer = 'Summer',
  Fall = 'Fall',
  Spring = 'Spring'
}

export enum DayOfWeek {
  SUNDAY = 'SUNDAY',
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY'
}

export enum FEWeekday {
  SUNDAY = 'SUNDAY',
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY'
}

export const FEWeekdayToWeekday = {
  [FEWeekday.SUNDAY]: Weekday.Sunday,
  [FEWeekday.MONDAY]: Weekday.Monday,
  [FEWeekday.TUESDAY]: Weekday.Tuesday,
  [FEWeekday.WEDNESDAY]: Weekday.Wednesday,
  [FEWeekday.THURSDAY]: Weekday.Thursday,
  [FEWeekday.FRIDAY]: Weekday.Friday,
  [FEWeekday.SATURDAY]: Weekday.Saturday
};

// Rate Plan Payment Term Setting Enums
export enum SupportedPaymentMethodCodes {
  GUAINV = 'GUAINV', // Pay with invoice
  GUAWCC = 'GUAWCC', // Guarantee with credit card
  GUAWDE = 'GUAWDE', // Bank transfer
  NOGUAR = 'NOGUAR', // Reserve without credit card
  PAYPAL = 'PAYPAL', // PayPal
  PMDOTH = 'PMDOTH' // Other payment method
}

// Rate Plan Extra Service Enums
export enum RatePlanExtraServiceType {
  INCLUDED = 'INCLUDED',
  EXTRA = 'EXTRA',
  MANDATORY = 'MANDATORY'
}

//  Extra Service Enums
export enum ExtraServiceTypeEnum {
  INCLUDED = 'INCLUDED',
  EXTRA = 'EXTRA',
  MANDATORY = 'MANDATORY'
}

// Hotel Retail Feature Enums
export enum FeatureAdultsSuitabilityEnum {
  SINGLE = 'SINGLE',
  DOUBLE = 'DOUBLE',
  ALL = 'ALL'
}

export enum HotelRetailFeatureStatusEnum {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE'
}

export enum FeatureTypeEnum {
  AMENITY = 'AMENITY',
  SERVICE = 'SERVICE',
  FACILITY = 'FACILITY'
}

// Hotel Retail Category Enums
export enum CategoryTypeEnum {
  ONE_OPTION = 'ONE_OPTION',
  MULTIPLE_OPTION = 'MULTIPLE_OPTION'
}

// Hotel Restriction Setting Enums
export enum HotelRestrictionCodeEnum {
  RSTR_AVAILABLE_PERIOD = 'RSTR_AVAILABLE_PERIOD',
  RSTR_CLOSE_TO_ARRIVAL = 'RSTR_CLOSE_TO_ARRIVAL',
  RSTR_CLOSE_TO_DEPARTURE = 'RSTR_CLOSE_TO_DEPARTURE',
  RSTR_CLOSE_TO_STAY_SELLABILITY = 'RSTR_CLOSE_TO_STAY_SELLABILITY',
  RSTR_CLOSE_TO_STAY = 'RSTR_CLOSE_TO_STAY',
  RSTR_LOS_MAX = 'RSTR_LOS_MAX',
  RSTR_LOS_MIN = 'RSTR_LOS_MIN',
  RSTR_MAX_ADVANCE_BOOKING = 'RSTR_MAX_ADVANCE_BOOKING',
  RSTR_MIN_ADVANCE_BOOKING = 'RSTR_MIN_ADVANCE_BOOKING',
  RSTR_MIN_LOS_THROUGH = 'RSTR_MIN_LOS_THROUGH',
  RSTR_STAY_THROUGH_DAY = 'RSTR_STAY_THROUGH_DAY'
}

export enum RestrictionEntity {
  PROPERTY = 'PROPERTY',
  ROOM_PRODUCT = 'ROOM_PRODUCT',
  SALES_PLAN = 'SALES_PLAN',
  ROOM_PRODUCT_SALES_PLAN = 'ROOM_PRODUCT_SALES_PLAN'
}

export enum HotelRestrictionSettingMode {
  NEUTRAL = 'NEUTRAL',
  PULL = 'PULL',
  PUSH = 'PUSH'
}

// Template Amenity Enums
export enum AmenityTypeEnum {
  SERVICE = 'SERVICE',
  AMENITY = 'AMENITY',
  MEAL_PLAN = 'MEAL_PLAN',
  EXTRA_BED = 'EXTRA_BED'
}

export enum PricingUnitEnum {
  PERSON = 'PERSON',
  PER_PERSON_PER_ROOM = 'PER_PERSON_PER_ROOM',
  ITEM = 'ITEM',
  ROOM = 'ROOM',
  STAY = 'STAY',
  NIGHT = 'NIGHT'
}

export enum AmenityAvailabilityEnum {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  ONLY_ON_ARRIVAL = 'ONLY_ON_ARRIVAL',
  ONLY_ON_DEPARTURE = 'ONLY_ON_DEPARTURE'
}

// Hotel Enums
export enum HotelStatusEnum {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING'
}

export enum TaxSettingEnum {
  INCLUSIVE = 'INCLUSIVE',
  EXCLUSIVE = 'EXCLUSIVE'
}

export enum ServiceChargeSettingEnum {
  INCLUSIVE = 'INCLUSIVE',
  EXCLUSIVE = 'EXCLUSIVE'
}

export enum MeasureMetricEnum {
  SQFT = 'sqft',
  SQM = 'sqm'
}

// Hotel Tax Setting Enums
export enum ServiceTypeEnum {
  ACCOMMODATION = 'ACCOMMODATION',
  EXTRAS = 'EXTRAS'
}

// Hotel Payment Mode Enums
export enum HotelPaymentModeCodeEnum {
  NOGUAR = 'NOGUAR', // Reserve without credit card
  GUAWCC = 'GUAWCC', // Guarantee with credit card
  GUAWDE = 'GUAWDE', // Bank transfer
  GUAINV = 'GUAINV', // Pay with invoice
  PAYPAL = 'PAYPAL', //PayPal
  PMDOTH = 'PMDOTH', //Other Payment Method

  // TOTO remove
  CASH = 'CASH',
  BANK_TRANSFER = 'BANK_TRANSFER'
}

// Hotel Payment Method Setting Enums
export enum PaymentMethodStatusEnum {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING'
}

// Hotel Payment Account Enums
export enum PaymentAccountOriginEnum {
  SALES_ENGINE = 'SALES_ENGINE',
  EXTRANET = 'EXTRANET',
  PMS = 'PMS',
  MOBILE_APP = 'MOBILE_APP'
}

export enum PaymentAccountTypeEnum {
  ADYEN = 'ADYEN',
  STRIPE = 'STRIPE',
  MEWS_PAYMENT = 'MEWS_PAYMENT',
  PAYPAL = 'PAYPAL',
  SQUARE = 'SQUARE',
  GAUVENDI_PAY = 'GAUVENDI_PAY'
}

export enum PaymentEnvironmentEnum {
  TEST = 'TEST',
  LIVE = 'LIVE',
  SANDBOX = 'SANDBOX',
  PRODUCTION = 'PRODUCTION'
}

// Hotel Market Segment Enums
export enum MarketSegmentStatusEnum {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE'
}

// Hotel City Tax Enums
export enum CityTaxUnitEnum {
  PER_PERSON_PER_NIGHT = 'PER_PERSON_PER_NIGHT',
  PER_PERSON_PER_STAY_FIXED = 'PER_PERSON_PER_STAY_FIXED',
  PERCENTAGE_ON_GROSS_AMOUNT_ROOM = 'PERCENTAGE_ON_GROSS_AMOUNT_ROOM',
  PERCENTAGE_ON_NET_AMOUNT_ROOM = 'PERCENTAGE_ON_NET_AMOUNT_ROOM',
  FIXED_ON_GROSS_AMOUNT_ROOM = 'FIXED_ON_GROSS_AMOUNT_ROOM',
  PER_ROOM_PER_NIGHT = 'PER_ROOM_PER_NIGHT'
}

export enum CityTaxChargeMethodEnum {
  PAY_ON_CONFIRMATION = 'PAY_ON_CONFIRMATION',
  PAY_AT_HOTEL = 'PAY_AT_HOTEL'
}

export enum CityTaxStatusEnum {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING'
}

// Hotel Amenity Enums
export enum IsePricingDisplayModeEnum {
  EXCLUSIVE = 'EXCLUSIVE',
  INCLUSIVE = 'INCLUDED'
}

export enum AmenityStatusEnum {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DRAFT = 'DRAFT'
}

export enum SellingTypeEnum {
  SINGLE = 'SINGLE',
  PACKAGE = 'PACKAGE',
  COMBO = 'COMBO'
}

export enum DistributionChannelEnum {
  GV_SALES_ENGINE = 'GV_SALES_ENGINE',
  GV_VOICE = 'GV_VOICE'
}

// Hotel Age Category Enums
export enum HotelAgeCategoryCodeEnum {
  INFANT = 'INFANT',
  CHILD = 'CHILD',
  TEENAGER = 'TEENAGER',
  ADULT = 'ADULT',
  DEFAULT = 'DEFAULT'
}

// Global Payment Provider Enums
export enum GlobalPaymentProviderCodeEnum {
  PAYPAL = 'PAYPAL',
  APALEO_PAY = 'APALEO_PAY',
  GAUVENDI_PAY = 'GAUVENDI_PAY',
  MEWS_PAYMENT = 'MEWS_PAYMENT',
  ADYEN = 'ADYEN',
  OPI = 'OPI',
  ONE_PAY = 'ONE_PAY'
}

// Connector Enums
export enum ConnectorTypeEnum {
  APALEO = 'apaleo',
  MEWS = 'Mews',
  OHIP = 'Ohip'
}

export enum ConnectorStatusEnum {
  ACTIVE = 'ACTIVE',
  PENDING = 'PENDING',
  INACTIVE = 'INACTIVE'
}

export enum LanguageCodeEnum {
  EN = 'EN',
  FR = 'FR',
  DE = 'DE',
  IT = 'IT',
  ES = 'ES',
  NL = 'NL',
  AR = 'AR'
}

export interface Translation {
  languageCode: LanguageCodeEnum;
  name: string;
  description: string;
  payAtHotelDescription?: string;
  payOnConfirmationDescription?: string;
}

export enum HotelConfigurationTypeEnum {
  PRICE_SETTINGS = 'PRICE_SETTINGS',
  AUTOMATION_RESTRICTION_MAX_LOS = 'AUTOMATION_RESTRICTION_MAX_LOS',
  AVAILABLE_RFC_DISPLAY = 'AVAILABLE_RFC_DISPLAY',
  BORDER_COLOR = 'BORDER_COLOR',
  BRANDING_MARKETING = 'BRANDING_MARKETING',
  BUTTON_BACKGROUND_COLOR = 'BUTTON_BACKGROUND_COLOR',
  BUTTON_TEXT_COLOR = 'BUTTON_TEXT_COLOR',
  CANCELLATION_POLICY = 'CANCELLATION_POLICY',
  CAPACITY_SUITABILITY_SCORE = 'CAPACITY_SUITABILITY_SCORE',
  CHILDREN_BOOKING_ALLOWED = 'CHILDREN_BOOKING_ALLOWED',
  PET_POLICY = 'PET_POLICY',
  CHILDREN_POLICY = 'CHILDREN_POLICY',
  ADULT_POLICY = 'ADULT_POLICY',
  COLOR_ACCENT_1 = 'COLOR_ACCENT_1',
  COLOR_ACCENT_2 = 'COLOR_ACCENT_2',
  COLOR_ACCENT_3 = 'COLOR_ACCENT_3',
  COLOR_ACCENT_4 = 'COLOR_ACCENT_4',
  COLOR_ACCENT_5 = 'COLOR_ACCENT_5',
  COLOR_BACKGROUND_1 = 'COLOR_BACKGROUND_1',
  COLOR_BACKGROUND_2 = 'COLOR_BACKGROUND_2',
  COLOR_BACKGROUND_SPECIFIC = 'COLOR_BACKGROUND_SPECIFIC',
  COLOR_BOOKING_SUMMARY_BACKGROUND = 'COLOR_BOOKING_SUMMARY_BACKGROUND',
  COLOR_BORDER = 'COLOR_BORDER',
  COLOR_BTN_ADD_SERVICES_BACKGROUND = 'COLOR_BTN_ADD_SERVICES_BACKGROUND',
  COLOR_BTN_ADD_SERVICE_TEXT = 'COLOR_BTN_ADD_SERVICE_TEXT',
  COLOR_BTN_REMOVE_SERVICES_BACKGROUND = 'COLOR_BTN_REMOVE_SERVICES_BACKGROUND',
  COLOR_BUTTON_BACKGROUND = 'COLOR_BUTTON_BACKGROUND',
  COLOR_BUTTON_TEXT = 'COLOR_BUTTON_TEXT',
  COLOR_CALENDAR_MOBILE_BACKGROUND = 'COLOR_CALENDAR_MOBILE_BACKGROUND',
  COLOR_DIALOG_SELECT_CATEGORY_BACKGROUND = 'COLOR_DIALOG_SELECT_CATEGORY_BACKGROUND',
  COLOR_DIALOG_SELECT_FEATURE_BACKGROUND = 'COLOR_DIALOG_SELECT_FEATURE_BACKGROUND',
  COLOR_ERROR = 'COLOR_ERROR',
  COLOR_EXTRA_DETAIL_BACKGROUND = 'COLOR_EXTRA_DETAIL_BACKGROUND',
  COLOR_EXTRA_HEADER_BACKGROUND = 'COLOR_EXTRA_HEADER_BACKGROUND',
  COLOR_EXTRA_SERVICES_ITEM_BACKGROUND = 'COLOR_EXTRA_SERVICES_ITEM_BACKGROUND',
  COLOR_FEATURE_MATCHED = 'COLOR_FEATURE_MATCHED',
  COLOR_FEATURE_TAG_BACKGROUND = 'COLOR_FEATURE_TAG_BACKGROUND',
  COLOR_FEATURE_UNMATCHED = 'COLOR_FEATURE_UNMATCHED',
  COLOR_FILTER_OVERLAY_BACKGROUND = 'COLOR_FILTER_OVERLAY_BACKGROUND',
  COLOR_FOOTER_BACKGROUND = 'COLOR_FOOTER_BACKGROUND',
  COLOR_FOOTER_TEXT = 'COLOR_FOOTER_TEXT',
  COLOR_GUEST_INFORMATION_BACKGROUND = 'COLOR_GUEST_INFORMATION_BACKGROUND',
  COLOR_LOGO_BACKGROUND = 'COLOR_LOGO_BACKGROUND',
  COLOR_MAIN_BACKGROUND = 'COLOR_MAIN_BACKGROUND',
  COLOR_NAVIGATION_BACKGROUND = 'COLOR_NAVIGATION_BACKGROUND',
  COLOR_NAVIGATION_ICON = 'COLOR_NAVIGATION_ICON',
  COLOR_NAVIGATION_INDICATOR = 'COLOR_NAVIGATION_INDICATOR',
  COLOR_NAVIGATION_ITEM_TEXT = 'COLOR_NAVIGATION_ITEM_TEXT',
  COLOR_NAVIGATION_ITEM_TEXT_ACTIVE = 'COLOR_NAVIGATION_ITEM_TEXT_ACTIVE',
  COLOR_NAVIGATION_LINE_INDICATOR = 'COLOR_NAVIGATION_LINE_INDICATOR',
  COLOR_PAYMENT_DETAIL_BACKGROUND = 'COLOR_PAYMENT_DETAIL_BACKGROUND',
  COLOR_PAYMENT_INFORMATION_BACKGROUND = 'COLOR_PAYMENT_INFORMATION_BACKGROUND',
  COLOR_PAYMENT_POLICY_BACKGROUND = 'COLOR_PAYMENT_POLICY_BACKGROUND',
  COLOR_PAYMENT_RESULT_BACKGROUND = 'COLOR_PAYMENT_RESULT_BACKGROUND',
  COLOR_PAYMENT_RESULT_ITEM_EVEN_BACKGROUND = 'COLOR_PAYMENT_RESULT_ITEM_EVEN_BACKGROUND',
  COLOR_PAYMENT_RESULT_ITEM_ODD_BACKGROUND = 'COLOR_PAYMENT_RESULT_ITEM_ODD_BACKGROUND',
  COLOR_PAYMENT_RESULT_SUB_TEXT = 'COLOR_PAYMENT_RESULT_SUB_TEXT',
  COLOR_PAYMENT_RESULT_TEXT = 'COLOR_PAYMENT_RESULT_TEXT',
  COLOR_PAYMENT_RESULT_TITLE_BACKGROUND = 'COLOR_PAYMENT_RESULT_TITLE_BACKGROUND',
  COLOR_PAYMENT_RESULT_TOTAL_BACKGROUND = 'COLOR_PAYMENT_RESULT_TOTAL_BACKGROUND',
  COLOR_PRICE = 'COLOR_PRICE',
  COLOR_PRIMARY = 'COLOR_PRIMARY',
  COLOR_RATE_PLAN_BACKGROUND = 'COLOR_RATE_PLAN_BACKGROUND',
  COLOR_RATE_PLAN_BACKGROUND_AFTER = 'COLOR_RATE_PLAN_BACKGROUND_AFTER',
  COLOR_RATE_PLAN_ITEM_BACKGROUND = 'COLOR_RATE_PLAN_ITEM_BACKGROUND',
  COLOR_RATE_PLAN_PANEL_BACKGROUND = 'COLOR_RATE_PLAN_PANEL_BACKGROUND',
  COLOR_RATE_PLAN_PANEL_TEXT = 'COLOR_RATE_PLAN_PANEL_TEXT',
  COLOR_RATE_PLAN_TEXT = 'COLOR_RATE_PLAN_TEXT',
  COLOR_ROOM_DETAIL_BACKGROUND = 'COLOR_ROOM_DETAIL_BACKGROUND',
  COLOR_ROOM_LOCK_RESTRICTION = 'COLOR_ROOM_LOCK_RESTRICTION',
  COLOR_SEARCH_BAR_BACKGROUND = 'COLOR_SEARCH_BAR_BACKGROUND',
  COLOR_SEARCH_BAR_ICON = 'COLOR_SEARCH_BAR_ICON',
  COLOR_SEARCH_BAR_SECTION_BACKGROUND = 'COLOR_SEARCH_BAR_SECTION_BACKGROUND',
  COLOR_SEARCH_BAR_TITLE = 'COLOR_SEARCH_BAR_TITLE',
  COLOR_SEARCH_BAR_VALUE = 'COLOR_SEARCH_BAR_VALUE',
  COLOR_SEARCH_FEATURE_BACKGROUND_SELECTED = 'COLOR_SEARCH_FEATURE_BACKGROUND_SELECTED',
  COLOR_SEARCH_FEATURE_BORDER = 'COLOR_SEARCH_FEATURE_BORDER',
  COLOR_SEARCH_FEATURE_ICON = 'COLOR_SEARCH_FEATURE_ICON',
  COLOR_SEARCH_FEATURE_ICON_SELECTED = 'COLOR_SEARCH_FEATURE_ICON_SELECTED',
  COLOR_SEARCH_FEATURE_TEXT = 'COLOR_SEARCH_FEATURE_TEXT',
  COLOR_SEARCH_FEATURE_TEXT_SELECTED = 'COLOR_SEARCH_FEATURE_TEXT_SELECTED',
  COLOR_SECONDARY_1 = 'COLOR_SECONDARY_1',
  COLOR_SECONDARY_2 = 'COLOR_SECONDARY_2',
  COLOR_SECONDARY_3 = 'COLOR_SECONDARY_3',
  COLOR_SERVICES_ADDED_BACKGROUND = 'COLOR_SERVICES_ADDED_BACKGROUND',
  COLOR_SUB_TEXT = 'COLOR_SUB_TEXT',
  COLOR_SUCCESS = 'COLOR_SUCCESS',
  COLOR_SUGGESTION_FEATURE_ITEM_BACKGROUND = 'COLOR_SUGGESTION_FEATURE_ITEM_BACKGROUND',
  COLOR_SUGGESTION_ITEM_BACKGROUND = 'COLOR_SUGGESTION_ITEM_BACKGROUND',
  COLOR_TAB_INK_ROOM_DETAIL = 'COLOR_TAB_INK_ROOM_DETAIL',
  COLOR_TAB_ROOM_DETAIL_BACKGROUND = 'COLOR_TAB_ROOM_DETAIL_BACKGROUND',
  COLOR_TEXT = 'COLOR_TEXT',
  COLOR_TEXT_SPECIFIC = 'COLOR_TEXT_SPECIFIC',
  COLOR_WARNING = 'COLOR_WARNING',
  CPP_VIEW_MODE = 'CPP_VIEW_MODE',
  CUSTOM_THEME_BACKGROUND = 'CUSTOM_THEME_BACKGROUND',
  DEFAULT_BOOKING_ROOM_STATUS = 'DEFAULT_BOOKING_ROOM_STATUS',
  DEFAULT_LANGUAGE = 'DEFAULT_LANGUAGE',
  DEFAULT_PAX = 'DEFAULT_PAX',
  DEFAULT_STAY_NIGHT = 'DEFAULT_STAY_NIGHT',
  DISABLE_STAY_OPTION_PRICE_CLUSTERING = 'DISABLE_STAY_OPTION_PRICE_CLUSTERING',
  POPULAR_AI_RECOMMENDATION_SETTING = 'POPULAR_AI_RECOMMENDATION_SETTING',
  OUR_TIP_AI_RECOMMENDATION_SETTING = 'OUR_TIP_AI_RECOMMENDATION_SETTING',
  EVENT_RELEVANT_SCORE = 'EVENT_RELEVANT_SCORE',
  FEATURE_POPULARITY_SCORE = 'FEATURE_POPULARITY_SCORE',
  FONT_FAMILY_PRIMARY = 'FONT_FAMILY_PRIMARY',
  GAUVENDI_LOGO_FOOTER = 'GAUVENDI_LOGO_FOOTER',
  IMPRESSUM_URL = 'IMPRESSUM_URL',
  ISE_CALENDAR_ADDITIONAL_INFORMATION_DISPLAY = 'ISE_CALENDAR_ADDITIONAL_INFORMATION_DISPLAY',
  ISE_PRICING_DISPLAY = 'ISE_PRICING_DISPLAY',
  LAST_OPENING_AVAILABILITY_DATE = 'LAST_OPENING_AVAILABILITY_DATE',
  LAYOUT_SETTING = 'LAYOUT_SETTING',
  LOGO_URL = 'LOGO_URL',
  MANDATORY_GUEST_INPUT = 'MANDATORY_GUEST_INPUT',
  NAVIGATION_BACKGROUND_COLOR = 'NAVIGATION_BACKGROUND_COLOR',
  NAVIGATION_ITEM_COLOR = 'NAVIGATION_ITEM_COLOR',
  NAVIGATION_ITEM_TEXT_COLOR = 'NAVIGATION_ITEM_TEXT_COLOR',
  PENALTY_SCORE = 'PENALTY_SCORE',
  POPULAR_FEATURE_LIMIT = 'POPULAR_FEATURE_LIMIT',
  PRICING_DECIMAL_ROUNDING_RULE = 'PRICING_DECIMAL_ROUNDING_RULE',
  PRIMARY_COLOR = 'PRIMARY_COLOR',
  PRIORITY_WEIGHT = 'PRIORITY_WEIGHT',
  PRIOR_DAYS_TRIGGER_UPDATE_BOOKING_ROOM_STATUS = 'PRIOR_DAYS_TRIGGER_UPDATE_BOOKING_ROOM_STATUS',
  PRIVACY_STATEMENT_URL = 'PRIVACY_STATEMENT_URL',
  PROPERTY_BRANDING = 'PROPERTY_BRANDING',
  RECEPTION_OPERATION_CLOSING = 'RECEPTION_OPERATION_CLOSING',
  RECEPTION_OPERATION_CLOSING_PMS_SYNC = 'RECEPTION_OPERATION_CLOSING_PMS_SYNC',
  RECEPTION_OPERATION_CLOSING_CHANNEL_SYNC = 'RECEPTION_OPERATION_CLOSING_CHANNEL_SYNC', // upcoming
  RETAIL_CATEGORY_BACKGROUND = 'RETAIL_CATEGORY_BACKGROUND',
  ROOM_PRODUCT_RECOMMENDATION_CONFIGURATOR_SETTING = 'ROOM_PRODUCT_RECOMMENDATION_CONFIGURATOR_SETTING',
  ROOM_PRODUCT_RECOMMENDATION_DIRECT_SETTING = 'ROOM_PRODUCT_RECOMMENDATION_DIRECT_SETTING',
  ROOM_PRODUCT_RECOMMENDATION_GRADED_LABEL_SETTING = 'ROOM_PRODUCT_RECOMMENDATION_GRADED_LABEL_SETTING',
  ROOM_PRODUCT_RESTRICTION_CONDITION = 'ROOM_PRODUCT_RESTRICTION_CONDITION',
  SECONDARY_COLOR = 'SECONDARY_COLOR',
  SERVICE_CHARGE_SETTING = 'SERVICE_CHARGE_SETTING',
  STAY_OPTION_RECOMMENDATION_SETTING = 'STAY_OPTION_RECOMMENDATION_SETTING',
  TAX_INFORMATION = 'TAX_INFORMATION',
  TERMS_OF_USE_URL = 'TERMS_OF_USE_URL',
  TEXT_COLOR = 'TEXT_COLOR',
  TIME_SLICE_CONFIGURATION = 'TIME_SLICE_CONFIGURATION',
  VAT_SETTING = 'VAT_SETTING',
  WHITELABEL_SETTING = 'WHITELABEL_SETTING',
  WIDGET_SETTING = 'WIDGET_SETTING',
  ISE_URL = 'ISE_URL',
  FAVICON_IMAGE_URL = 'FAVICON_IMAGE_URL',
  BOOKING_SETTINGS = 'BOOKING_SETTINGS',
  PRICING_SETTINGS = 'PRICING_SETTINGS',
  UI_THEME_SETTINGS = 'UI_THEME_SETTINGS',
  AVAILABILITY_SETTINGS = 'AVAILABILITY_SETTINGS',
  AUTOMATION_ROOM_LOCKING = 'AUTOMATION_ROOM_LOCKING',
  ISE_FEATURE_SORTING_DISPLAY = 'ISE_FEATURE_SORTING_DISPLAY',

  // Integrations configs
  GOOGLE_ANALYTICS = 'GOOGLE_ANALYTICS',
  GOOGLE_ADS = 'GOOGLE_ADS',
  GTM = 'GTM',
  META_CONVERSION = 'META_CONVERSION',
  DUETTO_CONFIGURATION = 'DUETTO_CONFIGURATION',
  USERCENTRICS_CMP_SETTING = 'USERCENTRICS_CMP_SETTING',
  COOKIEBOT_CONFIGURATION = 'COOKIEBOT_CONFIGURATION',
  DOCK_WCAG = 'DOCK_WCAG'
}

export enum PropertyMarketingTypeEnum {
  GoogleAds = 'GOOGLE_ADS',
  GoogleAnalytics = 'GOOGLE_ANALYTICS',
  GoogleTagManager = 'GOOGLE_TAG_MANAGER',
  MetaConversion = 'META_CONVERSION'
}

export enum PropertyTrackingTypeEnum {
  Cookiebot = 'COOKIEBOT',
  Duetto = 'DUETTO',
  UsercentricsCmp = 'USERCENTRICS_CMP'
}

export enum BookingFlow {
  LOWEST_PRICE = 'LOWEST_PRICE',
  MOST_POPULAR = 'MOST_POPULAR',
  DIRECT = 'DIRECT',
  MATCH = 'MATCH',
  OPERATOR = 'OPERATOR',
  OTHER = 'OTHER',
  RECOMMENDED = 'RECOMMENDED',
  VOICE = 'VOICE',
  CALL_PRO_PLUS = 'CALL_PRO_PLUS'
}

export enum HotelAmenityCodeSurchargeEnum {
  EXTRA_BED_ADULT_AMENITY_CODE = 'EXTRA_BED_ADULT',
  PET_AMENITY_CODE = 'PET_SURCHARGE',
  EXTRA_BED_KID_AMENITY_CODE = 'EXTRA_BED_KID',
  SERVICE_CHARGE_TAX_SERVICE_CODE = 'SERVICE_CHARGE'
}

export enum RestrictionLevel {
  ROOM_PRODUCT = 'room_product',
  RATE_PLAN = 'rate_plan',
  HOUSE_LEVEL = 'house_level',
  ROOM_PRODUCT_RATE_PLAN = 'room_product_rate_plan'
}
export enum DayOfWeek {
  Friday = 'FRIDAY',
  Monday = 'MONDAY',
  Saturday = 'SATURDAY',
  Sunday = 'SUNDAY',
  Thursday = 'THURSDAY',
  Tuesday = 'TUESDAY',
  Wednesday = 'WEDNESDAY'
}

export const DayOfWeekJs = {
  [DayOfWeek.Sunday]: 0,
  [DayOfWeek.Monday]: 1,
  [DayOfWeek.Tuesday]: 2,
  [DayOfWeek.Wednesday]: 3,
  [DayOfWeek.Thursday]: 4,
  [DayOfWeek.Friday]: 5,
  [DayOfWeek.Saturday]: 6
};

export enum RatePlanDerivedSettingInheritedFields {
  minLength = 'minLength',
  maxLength = 'maxLength',
  minAdv = 'minAdv',
  maxAdv = 'maxAdv',
  minLosThrough = 'minLosThrough',
  maxReservationCount = 'maxReservationCount'
}

export enum ResponseStatusEnum {
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR'
}

export enum ResponseCodeEnum {
  SUCCESS = '200',
  PENDING = '202',
  ERROR = '400'
}

export enum ReservationFilterDateType {
  ARRIVAL = 'ARRIVAL',
  STAY_IN = 'STAY_IN'
}
